using Microsoft.Extensions.Configuration;
using UrlShortener.Api.DTOs;
using UrlShortener.Api.Services;

namespace UrlShortener.Api.Tests;

public class UrlServiceTests
{
    private static UrlService CreateService(FakeUrlRepository? repository = null)
    {
        var configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ShortUrl:BaseUrl"] = "https://gul.fy",
            })
            .Build();

        return new UrlService(repository ?? new FakeUrlRepository(), new Base62Service(), configuration);
    }

    [Fact]
    public async Task CreateUrl_NormalizesSchemelessUrl()
    {
        var service = CreateService();

        var response = await service.CreateUrl("example.com/path");

        Assert.Equal("https://example.com/path", response.OriginalUrl);
    }

    [Fact]
    public async Task CreateUrl_BuildsShortUrlFromBaseUrlAndCode()
    {
        var service = CreateService();

        var response = await service.CreateUrl("https://example.com");

        Assert.Equal($"https://gul.fy/{response.Code}", response.ShortUrl);
    }

    [Theory]
    [InlineData("not a url")]
    [InlineData("")]
    [InlineData("   ")]
    public async Task CreateUrl_RejectsInvalidUrl(string originalUrl)
    {
        var service = CreateService();

        await Assert.ThrowsAsync<InvalidUrlException>(() => service.CreateUrl(originalUrl));
    }

    [Fact]
    public async Task CreateUrl_WithCustomCode_UsesItAsTheCode()
    {
        var service = CreateService();

        var response = await service.CreateUrl("https://example.com", customCode: "Coffee");

        Assert.Equal("Coffee", response.Code);
        Assert.Equal("Coffee", response.CustomCode);
        Assert.Equal("https://gul.fy/Coffee", response.ShortUrl);
    }

    [Fact]
    public async Task CreateUrl_RejectsCustomCodeWithInvalidCharacters()
    {
        var service = CreateService();

        var ex = await Assert.ThrowsAsync<InvalidUrlException>(
            () => service.CreateUrl("https://example.com", customCode: "my name!"));

        Assert.Contains("letters, numbers, hyphens, and underscores", ex.Message);
    }

    [Fact]
    public async Task CreateUrl_RejectsCustomCodeAlreadyTakenByAnotherLink()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        await service.CreateUrl("https://example.com/a", customCode: "Coffee");

        var ex = await Assert.ThrowsAsync<InvalidUrlException>(
            () => service.CreateUrl("https://example.com/b", customCode: "Coffee"));

        Assert.Contains("\"Coffee\" is already taken", ex.Message);
    }

    [Fact]
    public async Task CreateUrl_RejectsCustomCodeCollidingWithAnotherLinksAutoCode()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var first = await service.CreateUrl("https://example.com/a");

        var ex = await Assert.ThrowsAsync<InvalidUrlException>(
            () => service.CreateUrl("https://example.com/b", customCode: first.Code));

        Assert.Contains("already taken", ex.Message);
    }

    [Fact]
    public async Task CreateUrl_BlankCustomCodeIsTreatedAsNoCustomCode()
    {
        var service = CreateService();

        var response = await service.CreateUrl("https://example.com", customCode: "   ");

        Assert.Null(response.CustomCode);
    }

    [Fact]
    public async Task CreateUrl_RejectsDuplicatePlatformTargets()
    {
        var service = CreateService();

        await Assert.ThrowsAsync<InvalidUrlException>(() => service.CreateUrl(
            "https://example.com",
            platformTargets: [new PlatformTarget("android", "https://a.com"), new PlatformTarget("Android", "https://b.com")]));
    }

    [Fact]
    public async Task CreateUrl_NormalizesPlatformNamesToLowercase()
    {
        var service = CreateService();

        var response = await service.CreateUrl(
            "https://example.com",
            platformTargets: [new PlatformTarget("ANDROID", "example.com/app")]);

        var target = Assert.Single(response.PlatformTargets);
        Assert.Equal("android", target.Platform);
        Assert.Equal("https://example.com/app", target.Url);
    }

    [Fact]
    public async Task GetUrl_ResolvesByCustomCode()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        await service.CreateUrl("https://example.com/page", customCode: "Coffee");

        var response = await service.GetUrl("Coffee");

        Assert.NotNull(response);
        Assert.Equal("https://example.com/page", response!.OriginalUrl);
    }

    [Fact]
    public async Task GetUrl_ResolvesByAutoGeneratedCodeEvenAfterCustomCodeIsSet()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com");
        await service.UpdateUrl(created.Code, originalUrl: null, isActive: null, customCode: "Coffee");

        var response = await service.GetUrl(created.Code);

        Assert.NotNull(response);
        Assert.Equal("Coffee", response!.CustomCode);
    }

    [Fact]
    public async Task GetUrl_ReturnsNullForUnknownCode()
    {
        var service = CreateService();

        var response = await service.GetUrl("doesnotexist");

        Assert.Null(response);
    }

    [Fact]
    public async Task UpdateUrl_NullCustomCodeLeavesItUntouched()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com", customCode: "Coffee");

        var updated = await service.UpdateUrl(created.Code, originalUrl: "https://example.com/new", isActive: null);

        Assert.Equal("Coffee", updated!.CustomCode);
    }

    [Fact]
    public async Task UpdateUrl_EmptyCustomCodeClearsIt()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com", customCode: "Coffee");

        var updated = await service.UpdateUrl(created.Code, originalUrl: null, isActive: null, customCode: "");

        Assert.Null(updated!.CustomCode);
        Assert.Null(await service.GetUrl("Coffee"));
    }

    [Fact]
    public async Task UpdateUrl_CanRenameToANewCustomCode()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com", customCode: "Coffee");

        var updated = await service.UpdateUrl(created.Code, originalUrl: null, isActive: null, customCode: "Tea");

        Assert.Equal("Tea", updated!.CustomCode);
        Assert.Null(await service.GetUrl("Coffee"));
        Assert.NotNull(await service.GetUrl("Tea"));
    }

    [Fact]
    public async Task UpdateUrl_KeepingItsOwnCustomCodeIsNotTreatedAsACollision()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com", customCode: "Coffee");

        var updated = await service.UpdateUrl(created.Code, originalUrl: "https://example.com/new", isActive: null, customCode: "Coffee");

        Assert.Equal("Coffee", updated!.CustomCode);
        Assert.Equal("https://example.com/new", updated.OriginalUrl);
    }

    [Fact]
    public async Task UpdateUrl_RejectsRenamingToAnotherLinksCustomCode()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        await service.CreateUrl("https://example.com/a", customCode: "Coffee");
        var second = await service.CreateUrl("https://example.com/b");

        await Assert.ThrowsAsync<InvalidUrlException>(
            () => service.UpdateUrl(second.Code, originalUrl: null, isActive: null, customCode: "Coffee"));
    }

    [Fact]
    public async Task UpdateUrl_ReturnsNullForUnknownCode()
    {
        var service = CreateService();

        var updated = await service.UpdateUrl("doesnotexist", originalUrl: "https://example.com", isActive: null);

        Assert.Null(updated);
    }

    [Fact]
    public async Task DeleteUrl_RemovesLinkAndReturnsTrue()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com");

        var deleted = await service.DeleteUrl(created.Code);

        Assert.True(deleted);
        Assert.Null(await service.GetUrl(created.Code));
    }

    [Fact]
    public async Task DeleteUrl_ReturnsFalseForUnknownCode()
    {
        var service = CreateService();

        var deleted = await service.DeleteUrl("doesnotexist");

        Assert.False(deleted);
    }

    [Fact]
    public async Task GetRedirectTarget_FallsBackToDefaultForDesktopUserAgent()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl(
            "https://example.com/default",
            platformTargets: [new PlatformTarget("android", "https://example.com/android")]);

        var target = await service.GetRedirectTarget(created.Code, "Mozilla/5.0 (Windows NT 10.0; Win64; x64)");

        Assert.NotNull(target);
        Assert.True(target!.IsActive);
        Assert.Equal("https://example.com/default", target.DestinationUrl);
    }

    [Theory]
    [InlineData("Mozilla/5.0 (Linux; Android 14; Pixel 8)", "https://example.com/android")]
    [InlineData("Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)", "https://example.com/ios")]
    [InlineData("Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X)", "https://example.com/ios")]
    public async Task GetRedirectTarget_UsesMatchingPlatformOverride(string userAgent, string expectedUrl)
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl(
            "https://example.com/default",
            platformTargets:
            [
                new PlatformTarget("android", "https://example.com/android"),
                new PlatformTarget("ios", "https://example.com/ios"),
            ]);

        var target = await service.GetRedirectTarget(created.Code, userAgent);

        Assert.Equal(expectedUrl, target!.DestinationUrl);
    }

    [Fact]
    public async Task GetRedirectTarget_ReturnsNullForUnknownCode()
    {
        var service = CreateService();

        var target = await service.GetRedirectTarget("doesnotexist", userAgent: null);

        Assert.Null(target);
    }

    [Fact]
    public async Task GetRedirectTarget_Returns410StyleFlagForInactiveLink()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com");
        await service.UpdateUrl(created.Code, originalUrl: null, isActive: false);

        var target = await service.GetRedirectTarget(created.Code, userAgent: null);

        Assert.NotNull(target);
        Assert.False(target!.IsActive);
    }

    [Fact]
    public async Task GetRedirectTarget_RecordsAVisitWhenLinkIsActive()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl(
            "https://example.com",
            platformTargets: [new PlatformTarget("android", "https://example.com/android")]);

        await service.GetRedirectTarget(created.Code, "Mozilla/5.0 (Linux; Android 14)");

        var visit = Assert.Single(repository.RecordedVisits);
        Assert.Equal(created.Id, visit.Id);
        Assert.Equal("android", visit.MatchedPlatform);
    }

    [Fact]
    public async Task GetRedirectTarget_DoesNotRecordAVisitWhenLinkIsInactive()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com");
        await service.UpdateUrl(created.Code, originalUrl: null, isActive: false);

        await service.GetRedirectTarget(created.Code, userAgent: null);

        Assert.Empty(repository.RecordedVisits);
    }

    [Fact]
    public async Task GetRedirectTarget_DoesNotRecordAPlatformClickWhenFallingBackToDefault()
    {
        var repository = new FakeUrlRepository();
        var service = CreateService(repository);
        var created = await service.CreateUrl("https://example.com/default");

        await service.GetRedirectTarget(created.Code, "Mozilla/5.0 (Linux; Android 14)");

        var visit = Assert.Single(repository.RecordedVisits);
        Assert.Null(visit.MatchedPlatform);
    }
}
